# Generated by Django 4.1.1 on 2022-09-17 18:07

import django.core.validators
from django.db import migrations, models
import personal_portfolio.expenses_tracker.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Expense Image')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), personal_portfolio.expenses_tracker.validators.validate_only_chars], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), personal_portfolio.expenses_tracker.validators.validate_only_chars], verbose_name='Last Name')),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/', verbose_name='Profile Image')),
            ],
        ),
    ]
