# Generated by Django 4.1.1 on 2022-09-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expenses_tracker.profile'),
            preserve_default=False,
        ),
    ]
