# Generated by Django 4.1.1 on 2022-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0003_expense_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.URLField(verbose_name='Expense Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images',  verbose_name='Profile Image'),
        ),
    ]
